import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ReduxProvider from "@/components/redux/reduxProvider";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ACME STORE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <ReduxProvider>
            <div className="flex flex-col m-0 p-0">
              <div className="mb-20"><Navbar /></div>
              <div>{children}</div>
              <div><Footer/></div>
            </div>
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
