import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ReduxProvider from "@/components/redux/reduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ACME STORE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
        <Navbar/>
        {children}
        

        </ReduxProvider>
        
        </body>
    </html>
  );
}
